#服务器
server:
  port: 8081
  servlet:
    # 上下文配置 http://ip:port/demo/   未配置上下文 http://ip:port/
    context-path: /demo


# mybatis-plus
  mybatis-plus:
    # xml文件路径
    mapper-locations: classpath:mapper/*.xml
    # 实体类路径: 未生效
    type-aliases-package: com.springboot.demo.entry
    configuration:
      # 驼峰转换
      map-underscore-to-camel-case: true
      # 是否开启缓存
      cache-enabled: false
      # 打印sql
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

      # 全局配置
    global-config:
      # 数据库字段驼峰下划线转换
      db-column-underline: true
      # id自增类型(数据库id自增)
#      id-type: 0


#  mysql配置项
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: houj@123
    url: jdbc:mysql://localhost:3306/dbtest?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
